name: Tests
on: [ push ]

jobs:
  pytest:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: autoreduction/autoreduce-actions/build@master
        with:
          package_name: autoreduce_actions
